#!/bin/sh -ex

###################################
# setup nginx and php fastcgi

update-rc.d php-fastcgi defaults

mkdir -p /var/run/nginx
chown root:www-data /var/run/nginx
chmod 770 /var/run/nginx

###################################
# setup postgresql

PGSQL_VER=$(ls /etc/postgresql/)

# configure postgres to listen for remote connections
CONF=/etc/postgresql/$PGSQL_VER/main/postgresql.conf
sed --in-place "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $CONF

# configure postgres to accept remote connections
# TODO: listen only on loopback
cat >> /etc/postgresql/$PGSQL_VER/main/pg_hba.conf <<EOF
# Accept all IPv4 connections - CHANGE THIS!!!
host    all         all         0.0.0.0/0             md5
EOF

# TODO: fix this for nginx
sed -Ei "s|^(server.document-root.*=).*|\1 \"/var/www\"|" /etc/lighttpd/lighttpd.conf

# enable tklcp site
# TODO: nginx
lighty-enable-mod tklcp || true
