#!/bin/sh -ex

###################################
# setup nginx and php fastcgi

update-rc.d php-fastcgi defaults

mkdir -p /var/run/nginx
chown root:www-data /var/run/nginx
chmod 770 /var/run/nginx

###################################
# setup postgresql

PGSQL_VER=$(ls /etc/postgresql/)

# configure postgres to listen for remote connections
CONF=/etc/postgresql/$PGSQL_VER/main/postgresql.conf
sed --in-place "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $CONF

# TODO: replicate this, if needed, for nginx
#sed -Ei "s|^(server.document-root.*=).*|\1 \"/var/www\"|" /etc/lighttpd/lighttpd.conf

# enable tklcp site
# TODO: nginx
#lighty-enable-mod tklcp || true
